### PR TITLE
Add header generation

### PR DESCRIPTION
**Pull request by rachitnigam**
Adds new option `-h` that generates a header file if the given backend supports header generation.

@tedbauer can you test this for your use case before I merge this in?

### CODE REVIEW

**Comment by rachitnigam** [comment]
Merging this seems the basics seem to work. Will fix bugs as they come up.

**Comment by sa2257** [comment]
Does 'seem to work' mean 'generated a reasonable looking header file'? This doesn't also have an `include` keyword  which gets translated into `#include "fuse.h"` right? Put in another way, working header file doesn't mean it has a test does it?

**Comment by rachitnigam** [comment]
> This doesn't also have an `include` keyword which gets translated into `#include "fuse.h"` right?

All `import`s in the original Fuse file will still get translated into `#include` equivalents if that's what you're asking about.

**Comment by sa2257** [comment]
Ah great! So 'seem to work' means write a corresponding fuse header and write an `import` in `fuse` file and running the program? Awesome!

**Comment by rachitnigam** [comment]
Hm, I'm confused by this question. I don't think it does what you're saying. 
You should try running `fuse -h src/test/should-run/matadd.fuse` to see what the output looks like.

**Pull request merged**
