### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by KarlMobed**
Tried to replace and clarify a made up work "realizability"

### CODE REVIEW

**Comment by sa2257** [comment]
Also to clarify, "hardware realization" is a phrase used frequently in hardware design (Searching this in Google/ Google Scholar will verify that).

**Comment by KarlMobed** [comment]
Interesting information to learn.  I google or ask about cases like this in the future instead of siding with spellcheck and assuming a misspelling

**Comment by sa2257** [comment]
Essentially our abstractions should guarantee two things,
- They should be synthesizable in hardware (HLS tools by the way, for the most part guarantees this)
- They should be hardware friendly, that's to say, the designs should not be a naive emulation of C behavior and designed to leverage underlying hardware.

**Comment by rachitnigam** [comment]
Closing since there doesn't seem anything to do.

**Pull request closed without merging**
