### PR TITLE
Add partition experiment

### PR DESCRIPTION
**Pull request by rachitnigam**
C++ files for experiment described in #218.

Works with `make SOFTWARE=1` in both directories.

### CODE REVIEW

**Comment by sampsyo** [comment]
Added in this branch, with more fixes to make hardware execution actually work:
https://github.com/cucapra/fuse-benchmarks/tree/experiment-partitioning

**Comment by sampsyo** [comment]
Status so far:
- [manual-partition](http://localhost:8000/jobs/lMlAqThrvQ8.html) fails in estimation because the loop bounds need estimated trip count annotations.
- [using-pragma](http://localhost:8000/jobs/oTYgB2DPJYM.html) fails in HLS compilation because of more damn errors in the generated SDSoC host-side interface code. :cry: :scream: :angry:

(Those are links to proxied Buildbot pages, using my SSH tunnel trick described elsewhere.) This experiment can still work, but it will take some hammering to get it to go through SDSoC estimation.

**Comment by rachitnigam** [comment]
Okay, feel free to close this and discuss this in fuse-benchmarks instead.

> manual-partition fails in estimation because the loop bounds need estimated trip count annotations.

Is this with the top `while` loop? We can make `iterations` be a constant to make it work.

> using-pragma fails in HLS compilation because of more damn errors in the generated SDSoC host-side interface code.

Should I try porting to SDAccel?

**Comment by sampsyo** [comment]
OK! No need to move the discussion, but I did merge the (tweaked) code into `master` for convenience.

> Is this with the top `while` loop? We can make `iterations` be a constant to make it work.

Yes—although probably the right thing to do is to add estimated trip-count pragmas, like this:
https://github.com/cucapra/fuse-benchmarks/blob/ee826630c072347a7371c8df92a63db23a6eec81/rewrite/machsuite-viterbi/viterbi.cpp#L23

That is, something like this:

```
while (...) {
    decor "#pragma HLS loop_tripcount avg=42"
    ....
```

> Should I try porting to SDAccel?

Good question, but my intuition says no—I get the sense this should be debuggable, with a little fiddling with the function signature…

**Comment by sampsyo** [comment]
Also for future convenience, here's a copy-n-pastable command to check out tweaks:

```
./_scripts/batch.py experiments/partition/manual-partition experiments/partition/using-pragma
```

**Comment by rachitnigam** [comment]
Tracked in the benchmarks repo

**Pull request closed without merging**
