### PR TITLE
fixes #116

### LINKED ISSUE #116: Seashell generated C code has pointers not arrays
Previously generated [cpp](http://gorgonzola.cs.cornell.edu:8000/jobs/GHxxX5ed_8Q/files/code/gemm.cpp) for  `gemm`  example running on Buildbot

Currently failing [cpp](http://gorgonzola.cs.cornell.edu:8000/jobs/4htdM6yWs7c/files/code/gemm.cpp) for `gemm` example

### PR DESCRIPTION
**Pull request by rachitnigam**
Explicitly generate dimensions for arrays.

### CODE REVIEW

**Comment by sa2257** [comment]
It generates 2D array arguments. It should be 1D arrays.

```
void gemm(float m1[64][64], float m2[64][64], float prod[64][64]) {
  #pragma HLS ARRAY_PARTITION variable=m1 factor=64
  #pragma HLS ARRAY_PARTITION variable=m2 factor=64
  for(int i = 0; i < 64; i++) {
    
    for(int j = 0; j < 64; j++) {
      
      float sum = 0.0;
      for(int k = 0; k < 64; k++) {
        #pragma HLS UNROLL factor=64
        float mult = (m1[(i + (64 * k))] * m2[(k + (64 * j))]);
        // combiner:
        sum += mult;
      }
      prod[(i + (64 * j))] = sum;
      
    }
    
  }
}
void kernel() {
  
  
}
```

**Comment by rachitnigam** [comment]
Fixed.

**Comment by sa2257** [comment]
I think I updated the flattened change https://github.com/cucapra/seashell/compare/fix-116...integration-data_extraction

I get following error in `docker-compose build`

```
[info]   Compilation completed in 9.0s. 
[error] /seashell/src/main/scala/backends/VivadoBackend.scala:57
:14: value includes is not a member of fuselang.Syntax.Prog 
[error]       vsep(p.includes.map(emitInclude)) <@> 
[error]              ^      
[error] /seashell/src/main/scala/backends/VivadoBackend.scala:57
:27: not found: value emitInclude
[error]       vsep(p.includes.map(emitInclude)) <@>    
[error]                           ^                            
[error] /seashell/src/main/scala/backends/VivadoBackend.scala:58
:33: local val layout in method emitProg is never used 
[error]       vsep(p.defs.map(emitDef)) <@>    
[error]                                 ^                       
[error] /seashell/src/main/scala/backends/VivadoBackend.scala:55
:16: parameter value p in method emitProg is never used  
[error]   def emitProg(p: Prog, c: fuselang.Utils.Config): Strin
g = {                                                           
[error]                ^                                       
[error] /seashell/src/main/scala/backends/VivadoBackend.scala:55
:25: parameter value c in method emitProg is never used  
[error]   def emitProg(p: Prog, c: fuselang.Utils.Config): Strin
g = {                                                          
[error]                         ^                 
[error] 5 errors found                                         
[error] (Compile / compileIncremental) Compilation failed      
[error] Total time: 16 s, completed Mar 11, 2019 10:24:43 AM   
ERROR: Service 'workproc' failed to build: The command '/bin/sh 
-c sbt assembly' returned a non-zero code: 1 
```

**Comment by rachitnigam** [comment]
Try running the command:

sbt “; clean; assembly”

Class files might be in some inconsistent state. Also, make sure this branch is building locally on your computer. Since this branch builds on circle CI, the error points to a local issue.

**Comment by sa2257** [comment]
`sbt compile` is what's failing. It fails even with `clean`. As you point out `fix-116` works. So does up to commit dde7eaf14470cd56166007f1494fb607dc5d087a on `integration-data_extraction`. 
Merge fails due to line 57 I think `vsep(p.includes.map(emitInclude)) <@>`.  Can you tell me what this does?

https://github.com/cucapra/seashell/commit/3a02629f4026b227ebcea092833dedb2acd34000

**Comment by rachitnigam** [comment]
>   Can you tell me what this does?

This: https://github.com/cucapra/seashell/blob/master/src/main/scala/backends/CppLike.scala#L149

Seems like you didn't merge with master and instead just copied the code over. You can either create a merge commit or run `git checkout master && git pull && git rebase master`.

On a separate note, the script you're working with doesn't belong in this repo. You can simply work on a branch of fuse-benchmarks and use a master checkout of the compiler repo.

**Pull request merged**
