### PR TITLE
[WIP] MachSuite FFT

### PR DESCRIPTION
**Pull request by tedbauer**
[Link to original MachSuite program.](https://github.com/breagen/MachSuite/blob/master/fft/strided/fft.c)
## Compilation Status
~~Does not compile, due to (1).~~ Compiles!
## Issues 
~~1.  The problem decribed [here](https://github.com/cucapra/seashell/issues/79#issuecomment-465654713).~~
## Todo
- [X] Fix (1)
- [ ] Optimize with `bank` and `unroll`

### CODE REVIEW

**Comment by rachitnigam** [comment]
@tedbauer (1) was fixed. Is there a program that still fails?

**Comment by tedbauer** [comment]
I'm still getting this error message when I try to compile:
```
[Type error] [22.11] Expected subtype of idx((0,1), (0,32)) in assignment, received: int32.
			odd := odd | span;
			       ^
```

**Comment by rachitnigam** [comment]
Oh, wait, you can't reassign a loop iterator. This is meant to be an error.

**Comment by rachitnigam** [comment]
@tedbauer I've created https://github.com/cucapra/fuse-benchmarks. Let move these benchmarks under a folder titled `machsuite-direct-rewrite/` in that repo.

If you think a benchmark is particularly subtle, add it to the file tests. Let's talk tomorrow how we'll benchmark the code in that private repo.

If you don't have questions about this change, just close the benchmarking pull requests and add things in that repo.

**Pull request closed without merging**
